name: dowing_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  accordion: ^2.2.3
  advance_notification: ^1.0.6
  after_layout: ^1.2.0
  assorted_layout_widgets: ^6.0.0
  auto_route: ^4.0.1
  brasil_fields: ^1.4.2
  carousel_slider: ^4.0.0
  cpf_cnpj_validator: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  diacritic: ^0.1.3
  dio: ^4.0.4
  dio_logger: ^4.0.8+8
  dots_indicator: ^2.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^7.1.1
  flutter_mobx: ^2.0.5
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.0
  form_builder_extra_fields: ^8.1.0
  form_builder_validators: ^8.1.1
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  intl: ^0.17.0
  jiffy: ^5.0.0
  mobx: ^2.0.7
  path_provider: ^2.0.9
  pin_code_fields: ^7.4.0
  progress_stepper: ^1.0.0
  resize: ^1.0.0
  vimeo_player_flutter: ^0.0.3+2
  flutter_rating_bar: ^4.0.1
  share_plus: ^4.0.9
  expandable_text: ^2.3.0
  table_calendar: ^3.0.6
  just_the_tooltip: ^0.0.12
  flutter_multi_formatter: ^2.5.7
  url_launcher: ^6.1.4

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  mobx_codegen: ^2.0.7
  strict: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Milkshake
      fonts:
        - asset: assets/Milkshake.ttf
          weight: 400

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  build_clean: $clean & $get & $runner build --delete-conflicting-outputs
  watch_clean: $clean & $get & $runner watch --delete-conflicting-outputs
  watch: $get & $runner watch
  build: $clean & $get & $runner watch
